### ISSUE TITLE
Not installable via pip

### ISSUE THREAD

**Issue by damienstanton** [makism/dyfunconn#10]
Environment: Python 3.7.2 (running in venv module), macOS 10.14.3

```
(env) $ pip3 install dyfunconn
Collecting dyfunconn
  Could not find a version that satisfies the requirement dyfunconn (from versions: )
No matching distribution found for dyfunconn
```

I see that the module is not published on PyPi, so you might just need to change the README to explicitly point to the git repo (if that is the desired op). When searching for it on PyPi the only result that comes up is [Spektral](https://github.com/danielegrattarola/spektral).

**Comment by makism** [comment]
Hey Damien,

You are right, probably a release never made it to the official pip repository.
The testing repository should work though.

Thanks for the report, I am working on a maintenance/update right now so perhaps it's a nice opportunity to include your suggestion.

**Comment by makism** [comment]
Just pushed it on PyPi. Please let me if something else comes up.
