### ISSUE TITLE
No module called dyfunconn.plot 

### ISSUE THREAD

**Issue by akatav** [makism/dyfunconn#13]
Hi
I am interested in the topoplot() function. But I do not find it available in the dyfunconnpackage.

**Comment by makism** [comment]
Hey @akatav,

Thanks for your interest. Unfortunately, there's been a mixup with the private repository where some other (lower priority) developments take place.

The `plot` module is not yet publicly available.

Regards,
Makis

**Comment by akatav** [comment]
ok, will be nice to have it available too. thanks for the reply.

**Comment by balandongiv** [comment]
Late comer here.
I assume plot module is still in the back-burner as my compiler return the below error when using the latest dyconnmap version.

> ModuleNotFoundError: No module named 'dyconnmap.plot'

**Comment by makism** [comment]
Hey @balandongiv yeah, still not available; If you would like I can send you the code and you can hack around, but the code is pretty bad :-)

CC @akatav
