### ISSUE TITLE
Cannot download msdl data from tutorial about autism

### ISSUE THREAD

**Issue by devmessias** [makism/dyfunconn#14]
![image](https://user-images.githubusercontent.com/6979335/60621475-23189b00-9db4-11e9-9251-33fd0216a751.png)
![image](https://user-images.githubusercontent.com/6979335/60621484-2875e580-9db4-11e9-85a3-4a6460e99fec.png)

**Comment by makism** [comment]
Yes, that's a problem with the RAMP people, which I have no affiliation with.
Their certificates have expired. Use wget and the relevant options to circumvent SSL verification, also, please open a ticket to their issue page.
